# Generated by Django 5.1.5 on 2025-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
